import type { Metadata } from "next";

import { User } from "@supabase/supabase-js";

import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getUser()

  console.log(user)
  
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}


async function getUser(): Promise<User | undefined> {
  const supabase = await createClient()

  const user = await supabase.auth.getUser()

  if (!user || !user.data.user) {
    return undefined
  }

  console.log(user.data.user)

  return user.data.user
}